name: Continuous Integration

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3 
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{runner.os}}-go-${{hashFiles('**/go.sum')}}-test
          restore-keys: |
            ${{runner.os}}-go-
      - name: Test code
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.21.3 
      - name: Cache build
        uses: actions/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{runner.os}}-go-${{hashFiles('**/go.sum')}}-build
          restore-keys: |
            ${{runner.os}}-go-
      - name: Build linux binary
        run: |
          GOOS=linux go build
      - name: Build darwin binary
        run: |
          GOOS=darwin go build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3 
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{runner.os}}-go-${{hashFiles('**/go.sum')}}-test
          restore-keys: |
            ${{runner.os}}-go-
      - name: Lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          skip-go-installation: true
          args: --timeout=10m --verbose
      - name: Format code
        run: |
          if [ $(find . ! -path "./vendor/*" -name "*.go" -exec gofmt -s -d {} \;|wc -l) -gt 0 ]; then
           find . ! -path "./vendor/*" -name "*.go" -exec gofmt -s -d {} \;
           exit 1
          fi
      - name: errors
        run: golangci-lint run
        if: ${{ failure() }}
